# Numpy
#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices.
#NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.
#NumPy stands for Numerical Python.    

#Installation of NumPy
#Install it using this command:
C:\Users\Your Name>pip install numpy

In [1]:
#Import NumPy
import numpy

In [5]:
#Example
import numpy
arr = numpy.array([11, 62, 23, 64, 95])

print(arr)


[11 62 23 64 95]


In [8]:
#NumPy as np
#NumPy is usually imported under the np alias.

#Example
import numpy as np
arr = np.array([11, 32, 23, 64, 85])
print(arr)

[11 32 23 64 85]


In [11]:
#Checking NumPy Version

#Example
import numpy as np


print(np.__version__)

1.26.4


In [12]:
#NumPy Creating Arrays
#Create a NumPy ndarray Object
#NumPy is used to work with arrays. The array object in NumPy is called ndarray.
#We can create a NumPy ndarray object by using the array() function.


In [14]:
#Example
import numpy as np

arr = np.array([12, 32, 23, 44,25])

print(arr)

print(type(arr))

[12 32 23 44 25]
<class 'numpy.ndarray'>


In [15]:
#Dimensions in Arrays
#A dimension in arrays is one level of array depth (nested arrays).

In [18]:
#0-D Arrays
#0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

#Example
#Create a 0-D array with value 55

import numpy as np

arr = np.array(55)

print(arr)

55


In [20]:
#1-D Arrays
#An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.
#These are the most common and basic arrays.

#Example
#Create a 1-D array containing the values 41,12,33,24,65:

import numpy as np

arr = np.array([41, 12, 33, 24, 65])

print(arr)

[41 12 33 24 65]


In [21]:
#2-D Arrays
#An array that has 1-D arrays as its elements is called a 2-D array.
#These are often used to represent matrix or 2nd order tensors.

In [24]:
#Example
#Create a 2-D array containing two arrays with the values 11,62,23 and 34,15,56:

import numpy as np

arr = np.array([[11, 62,23], [34, 15,56]])

print(arr)


[[11 62 23]
 [34 15 56]]


In [25]:
#3-D arrays
#An array that has 2-D arrays (matrices) as its elements is called 3-D array.
#These are often used to represent a 3rd order tensor.

In [27]:
#Example
#Create a 3-D array with two 2-D arrays, both containing two arrays with the values 2,3,1 and 6,8.3

import numpy as np

arr = np.array([[[2,3,1], [6,8,3]], [[2,3,1], [6,8,3]]])

print(arr)

[[[2 3 1]
  [6 8 3]]

 [[2 3 1]
  [6 8 3]]]


In [29]:
#Check Number of Dimensions?
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

#Example
#Check how many dimensions the arrays have:

import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [31]:
#Higher Dimensional Arrays
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.

#Example
#Create an array with 5 dimensions and verify that it has 5 dimensions:

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [33]:
#NumPy Array Indexing
#Array indexing is the same as accessing an array element.

#The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [37]:
#ExampleGet your own Python Server
#Get the first element from the following array:

import numpy as np

arr = np.array([21, 72, 23,84])

print(arr[0])

21


In [39]:
#Example
#Get the second element from the following array.

import numpy as np

arr = np.array([41, 22, 83, 44])

print(arr[1])

22


In [41]:
#Example
#Get third and fourth elements from the following array and add them.

import numpy as np

arr = np.array([81, 12, 23, 74])

print(arr[2] + arr[3])

97


In [42]:
#Access 2-D Arrays
#To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

#Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [44]:
#Example
#Access the element on the first row, second column:

import numpy as np

arr = np.array([[21,12,53,34,65], [16,27,78,99,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  12


In [46]:
#Example
#Access the element on the 2nd row, 5th column:

import numpy as np

arr = np.array([[41,22,63,14,45], [66,72,28,39,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [48]:
#Access 3-D Arrays
#To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

#Example
#Access the third element of the second array of the first array:

import numpy as np

arr = np.array([[[21, 12, 43], [42, 25, 56]], [[27, 58, 79], [10, 31, 82]]])

print(arr[0, 1, 2])


56


In [50]:
#Negative Indexing
#Use negative indexing to access an array from the end.

#Example
#Print the last element from the 2nd dim:

import numpy as np

arr = np.array([[31,22,13,47,53], [62,79,82,49,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
#NumPy Array Slicing
Slicing arrays
Slicing in python means taking elements from one given index to another given index.
We pass slice instead of index like this: [start:end].
We can also define the step, like this: [start:end:step].
If we don't pass start its considered 0
If we don't pass end its considered length of array in that dimension
If we don't pass step its considered 1

In [52]:
#Example
#Slice elements from index 1 to index 5 from the following array:

import numpy as np

arr = np.array([13, 22, 63, 14, 65, 36, 47])

print(arr[1:5])

[22 63 14 65]


In [54]:
#Example
#Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([21, 42, 33, 84, 15, 86, 97])

print(arr[4:])


[15 86 97]


In [56]:
#Example
#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([12, 32, 43, 14,75, 36, 87])

print(arr[:4])

[12 32 43 14]


In [59]:
#Example
#Slice from the index 3 from the end to index 1 from the end:

import numpy as np

arr = np.array([61, 22, 33, 94, 25, 16,77])

print(arr[-3:-1])


[25 16]


In [62]:
#STEP
#Use the step value to determine the step of the slicing:

#Example
#Return every other element from index 1 to index 5:

import numpy as np

arr = np.array([11, 32, 23, 64, 56, 86, 97])

print(arr[1:5:2])



[32 64]


In [64]:
#Example
#Return every other element from the entire array:

import numpy as np

arr = np.array([21, 12, 33, 84, 25, 66, 47])

print(arr[::2])


[21 33 25 47]


In [67]:
#Slicing 2-D Arrays

#Example
#From the second element, slice elements from index 1 to index 4 (not included):

import numpy as np

arr = np.array([[12, 32, 23, 44, 75], [62, 47, 82, 39, 10]])

print(arr[1, 1:4])


[47 82 39]


In [70]:
#Example
#From both elements, return index 2:

import numpy as np

arr = np.array([[12, 22,63, 44, 25], [62, 37, 28, 69, 10]])

print(arr[0:2, 2])

[63 28]


In [72]:
#Example
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

import numpy as np

arr = np.array([[41, 32, 23, 74, 35], [76, 37, 18, 29, 10]])

print(arr[0:2, 1:4])

[[32 23 74]
 [37 18 29]]


In [ ]:
#NumPy Data Types
#Data Types in NumPy
#NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

#Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [74]:
#Checking the Data Type of an Array
#The NumPy array object has a property called dtype that returns the data type of the array:

#ExampleGet your own Python Server
#Get the data type of an array object:

import numpy as np

arr = np.array([11, 32,23, 54])

print(arr.dtype)

int32


In [2]:
#Example
#Get the data type of an array containing strings:

import numpy as np

arr = np.array(['pineapple', 'banana', 'mango'])

print(arr.dtype)

<U9


In [5]:
#Example
#Create an array with data type string:

import numpy as np

arr = np.array([71, 12, 23, 64], dtype='S')

print(arr)
print(arr.dtype)


[b'71' b'12' b'23' b'64']
|S2


In [7]:
#Example
#Create an array with data type 4 bytes integer:

import numpy as np

arr = np.array([81, 52, 23, 74], dtype='i4')

print(arr)
print(arr.dtype)

[81 52 23 74]
int32


In [9]:
#Converting Data Type on Existing Arrays
#The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

#The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

#The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

#Example
#Change data type from float to integer by using 'i' as parameter value:

import numpy as np

arr = np.array([12.1, 32.1, 73.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[12 32 73]
int32


In [11]:
#Example
#Change data type from float to integer by using int as parameter value:

import numpy as np

arr = np.array([11.1, 92.1, 33.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[11 92 33]
int32


In [14]:
#Example
#Change data type from integer to boolean:

import numpy as np

arr = np.array([31, 20, 43])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


In [17]:
#The Difference Between Copy and View
#The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
#The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

#Example

import numpy as np

arr = np.array([31, 42, 23, 64, 15])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42 42 23 64 15]
[31 42 23 64 15]


In [19]:
#Check if Array Owns its Data
#As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

#Every NumPy array has the attribute base that returns None if the array owns the data.

#Otherwise, the base  attribute refers to the original object.

#Example
#Print the value of the base attribute to check if an array owns it's data or not:

import numpy as np

arr = np.array([11, 32, 43, 24, 65])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[11 32 43 24 65]


In [23]:
#Shape of an Array
#The shape of an array is the number of elements in each dimension.
#NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

#Example
#Print the shape of a 2-D array:

import numpy as np

arr = np.array([[11, 32, 23, 64], [15, 56, 37, 28]])

print(arr.shape)


(2, 4)


In [25]:
#Example
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

import numpy as np

arr = np.array([21, 12, 63, 44], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[21 12 63 44]]]]]
shape of array : (1, 1, 1, 1, 4)


In [29]:
#NumPy Array Reshaping
#Reshaping arrays
#Reshaping means changing the shape of an array.
#The shape of an array is the number of elements in each dimension.
#By reshaping we can add or remove dimensions or change number of elements in each dimension.

#Reshape From 1-D to 2-D

#Example
#Convert the following 1-D array with 12 elements into a 2-D array.
#The outermost dimension will have 4 arrays, each with 3 elements:

import numpy as np

arr = np.array([11, 22, 13, 44, 75,36, 77, 28, 49, 10, 91, 12])

newarr = arr.reshape(4,3)

print(newarr)

[[11 22 13]
 [44 75 36]
 [77 28 49]
 [10 91 12]]


In [31]:
#Reshape From 1-D to 3-D
#Example
#Convert the following 1-D array with 12 elements into a 3-D array.
#The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

import numpy as np

arr = np.array([21, 12, 43, 34, 25, 76, 47, 98, 79, 10, 21, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[21 12]
  [43 34]
  [25 76]]

 [[47 98]
  [79 10]
  [21 12]]]


In [33]:
#Unknown Dimension
#You are allowed to have one "unknown" dimension.
#Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
#Pass-1 as the value, and NumPy will calculate this number for you.

#Example
#Convert 1D array with 8 elements to 3D array with 2x2 elements:

import numpy as np

arr = np.array([41, 12, 33, 64, 85, 56, 97, 28])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[41 12]
  [33 64]]

 [[85 56]
  [97 28]]]


In [35]:
#Flattening the arrays
#Flattening array means converting a multidimensional array into a 1D array.

#Example
#Convert the array into a 1D array:

import numpy as np

arr = np.array([[71, 22, 63], [14, 85, 36]])

newarr = arr.reshape(-1)

print(newarr)

[71 22 63 14 85 36]


In [37]:
#Iterating Arrays
#Iterating means going through elements one by one.
#As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.
#If we iterate on a 1-D array it will go through each element one by one.

#Example
#Iterate on the elements of the following 1-D array:

import numpy as np

arr = np.array([21, 62, 93])

for x in arr:
  print(x)

21
62
93


In [39]:
#Iterating 2-D Arrays
#In a 2-D array it will go through all the rows.

#Example
#Iterate on the elements of the following 2-D array:

import numpy as np

arr = np.array([[41, 12, 23], [34, 75, 86]])

for x in arr:
  print(x)

[41 12 23]
[34 75 86]


In [41]:
#Example
#Iterate on each scalar element of the 2-D array:

import numpy as np

arr = np.array([[61, 22, 33], [54, 85, 26]])

for x in arr:
  for y in x:
    print(y)

61
22
33
54
85
26


In [42]:
#Iterating 3-D Arrays
#In a 3-D array it will go through all the 2-D arrays.

#Example
#Iterate on the elements of the following 3-D array:

import numpy as np

arr = np.array([[[41, 12, 63], [24, 65, 26]], [[37, 18, 69], [10, 71, 22]]])

for x in arr:
  print(x)



[[41 12 63]
 [24 65 26]]
[[37 18 69]
 [10 71 22]]


In [49]:
#Example
#Iterate down to the scalars:

import numpy as np

arr = np.array([[[41, 12, 63], [24, 85, 46]], [[37, 78, 19], [10, 91, 22]]])

for x in arr:
    for y in x:
         for z in y:
            print(z)


41
12
63
24
85
46
37
78
19
10
91
22


In [51]:
#Iterating Arrays Using nditer()
#The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

#Example
#Iterate through the following 3-D array:

import numpy as np

arr = np.array([[[12, 42], [23, 54]], [[15, 96], [37, 28]]])

for x in np.nditer(arr):
  print(x)


12
42
23
54
15
96
37
28


In [53]:
#Iterating Array With Different Data Types
#We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.
#NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

#Example
#Iterate through the array as a string:

import numpy as np

arr = np.array([31, 22, 73])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'31'
b'22'
b'73'


In [55]:
#Example
#Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np

arr = np.array([[13, 32, 13, 44], [25, 16, 87, 28]])

for x in np.nditer(arr[:, ::2]):
  print(x)


13
13
25
87


In [57]:
#Enumerated Iteration Using ndenumerate()
#Enumeration means mentioning sequence number of somethings one by one.
#Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

#Example
#Enumerate on following 1D arrays elements:

import numpy as np

arr = np.array([31, 12, 63])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 31
(1,) 12
(2,) 63


In [59]:
#NumPy Joining Array
#Joining means putting contents of two or more arrays in a single array.
#In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

#Example
#Join two arrays

import numpy as np

arr1 = np.array([51, 22, 63])

arr2 = np.array([24, 65, 86])

arr = np.concatenate((arr1, arr2))

print(arr)


[51 22 63 24 65 86]


In [62]:
#Joining Arrays Using Stack Functions
#Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
#We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

#Example

import numpy as np

arr1 = np.array([21, 12, 53])

arr2 = np.array([34, 15, 76])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[21 34]
 [12 15]
 [53 76]]


In [64]:
#Stacking Along Rows
#NumPy provides a helper function: hstack() to stack along rows.

#Example
import numpy as np

arr1 = np.array([21, 12, 43])

arr2 = np.array([24, 45, 16])

arr = np.hstack((arr1, arr2))

print(arr)

[21 12 43 24 45 16]


In [66]:
#Stacking Along Columns
#NumPy provides a helper function: vstack()  to stack along columns.

#Example
import numpy as np

arr1 = np.array([21, 12, 43])

arr2 = np.array([74, 25, 66])

arr = np.vstack((arr1, arr2))

print(arr)

[[21 12 43]
 [74 25 66]]


In [68]:
#Stacking Along Height (depth)
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

#Example
import numpy as np

arr1 = np.array([51, 12, 23])

arr2 = np.array([34, 75, 26])

arr = np.dstack((arr1, arr2))

print(arr)

[[[51 34]
  [12 75]
  [23 26]]]


In [72]:
#NumPy Splitting Array
#Splitting is reverse operation of Joining.
#Joining merges multiple arrays into one and Splitting breaks one array into multiple.

#Example
#Split the array in 3 parts:

import numpy as np

arr = np.array([81, 32, 23,44, 65, 96])

newarr = np.array_split(arr, 2)

print(newarr)

[array([81, 32, 23]), array([44, 65, 96])]


In [74]:
#Split Into Arrays
#The return value of the array_split() method is an array containing each of the split as an array.

#Example
#Access the splitted arrays:

import numpy as np

arr = np.array([41, 12, 63, 24, 85, 46])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[41 12]
[63 24]
[85 46]


In [79]:
#NumPy Searching Arrays
#You can search an array for a certain value, and return the indexes that get a match.
#To search an array, use the where() method.

#Example
#Find the indexes where the value is 4:

import numpy as np

arr = np.array([41, 22, 53, 34, 85, 34, 74])

x = np.where(arr == 4)

print(x)


(array([], dtype=int64),)


In [81]:
#Example
#Find the indexes where the values are even:

import numpy as np

arr = np.array([21, 12, 33, 54, 45, 66, 97, 28])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [83]:
#Example
#Find the indexes where the values are odd:

import numpy as np

arr = np.array([31, 12, 73, 24, 75, 86, 97, 38])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [89]:
#Search Sorted
#There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

#The searchsorted() method is assumed to be used on sorted arrays.

#Example
#Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([16, 27, 58, 89])

x = np.searchsorted(arr, 27)

print(x)


1


In [91]:
#Search From the Right Side
#By default the left most index is returned, but we can give side='right' to return the right most index instead.

#Example
#Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([16, 47, 28, 79])

x = np.searchsorted(arr, 28, side='right')

print(x)

3


In [94]:
#Multiple Values
#To search for more than one value, use an array with the specified values.

#Example
#Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([11, 33, 25, 57])

x = np.searchsorted(arr, [22, 44, 86])

print(x)

[1 3 4]


In [97]:
#NumPy Sorting Arrays
#Sorting Arrays
#Sorting means putting elements in an ordered sequence.
#Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

#Example
#Sort the array:

import numpy as np

arr = np.array([23, 12, 40, 61])

print(np.sort(arr))

[12 23 40 61]


In [99]:
#Sorting a 2-D Array
#If you use the sort() method on a 2-D array, both arrays will be sorted:

#Example
#Sort a 2-D array:

import numpy as np

arr = np.array([[13, 20, 43], [52, 30, 41]])

print(np.sort(arr))

[[13 20 43]
 [30 41 52]]


In [101]:
#NumPy Filter Array
#Getting some elements out of an existing array and creating a new array out of them is called filtering.
#In NumPy, you filter an array using a boolean index list.

#Example
#Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [104]:
#Creating the Filter Array
#In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

#Example
#Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[True, False, False, False]
[41]


In [106]:
#Example
#Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([21, 12, 33, 54, 65, 86, 27])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[12 54 86]
